# Python stubs generated by omniidl from msipbias/corba/biascorba.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "BiasCorba"
#
__name__ = "msipbias.corba.BiasCorba"
_0_BiasCorba = omniORB.openModule("msipbias.corba.BiasCorba", r"msipbias/corba/biascorba.idl")
_0_BiasCorba__POA = omniORB.openModule("msipbias.corba.BiasCorba__POA", r"msipbias/corba/biascorba.idl")


# interface BiasModuleCorba
_0_BiasCorba._d_BiasModuleCorba = (omniORB.tcInternal.tv_objref, "IDL:BiasCorba/BiasModuleCorba:1.0", "BiasModuleCorba")
omniORB.typeMapping["IDL:BiasCorba/BiasModuleCorba:1.0"] = _0_BiasCorba._d_BiasModuleCorba
_0_BiasCorba.BiasModuleCorba = omniORB.newEmptyClass()
class BiasModuleCorba :
    _NP_RepositoryId = _0_BiasCorba._d_BiasModuleCorba[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_BiasCorba.BiasModuleCorba = BiasModuleCorba
_0_BiasCorba._tc_BiasModuleCorba = omniORB.tcInternal.createTypeCode(_0_BiasCorba._d_BiasModuleCorba)
omniORB.registerType(BiasModuleCorba._NP_RepositoryId, _0_BiasCorba._d_BiasModuleCorba, _0_BiasCorba._tc_BiasModuleCorba)

# BiasModuleCorba operations and attributes
BiasModuleCorba._d_getTemperature = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getMagnetCurrent = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getMagnetVoltage = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getSISVoltage = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getSISCurrent = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getLNADrainVoltage = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getLNADrainCurrent = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getLNAGateVoltage = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_setMagnetCurrent = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (), None)
BiasModuleCorba._d_setSISVoltage = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (), None)
BiasModuleCorba._d_setLNADrainVoltage = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (), None)
BiasModuleCorba._d_setLNADrainCurrent = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (), None)

# BiasModuleCorba object reference
class _objref_BiasModuleCorba (CORBA.Object):
    _NP_RepositoryId = BiasModuleCorba._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def getTemperature(self, *args):
        return _omnipy.invoke(self, "getTemperature", _0_BiasCorba.BiasModuleCorba._d_getTemperature, args)

    def getMagnetCurrent(self, *args):
        return _omnipy.invoke(self, "getMagnetCurrent", _0_BiasCorba.BiasModuleCorba._d_getMagnetCurrent, args)

    def getMagnetVoltage(self, *args):
        return _omnipy.invoke(self, "getMagnetVoltage", _0_BiasCorba.BiasModuleCorba._d_getMagnetVoltage, args)

    def getSISVoltage(self, *args):
        return _omnipy.invoke(self, "getSISVoltage", _0_BiasCorba.BiasModuleCorba._d_getSISVoltage, args)

    def getSISCurrent(self, *args):
        return _omnipy.invoke(self, "getSISCurrent", _0_BiasCorba.BiasModuleCorba._d_getSISCurrent, args)

    def getLNADrainVoltage(self, *args):
        return _omnipy.invoke(self, "getLNADrainVoltage", _0_BiasCorba.BiasModuleCorba._d_getLNADrainVoltage, args)

    def getLNADrainCurrent(self, *args):
        return _omnipy.invoke(self, "getLNADrainCurrent", _0_BiasCorba.BiasModuleCorba._d_getLNADrainCurrent, args)

    def getLNAGateVoltage(self, *args):
        return _omnipy.invoke(self, "getLNAGateVoltage", _0_BiasCorba.BiasModuleCorba._d_getLNAGateVoltage, args)

    def setMagnetCurrent(self, *args):
        return _omnipy.invoke(self, "setMagnetCurrent", _0_BiasCorba.BiasModuleCorba._d_setMagnetCurrent, args)

    def setSISVoltage(self, *args):
        return _omnipy.invoke(self, "setSISVoltage", _0_BiasCorba.BiasModuleCorba._d_setSISVoltage, args)

    def setLNADrainVoltage(self, *args):
        return _omnipy.invoke(self, "setLNADrainVoltage", _0_BiasCorba.BiasModuleCorba._d_setLNADrainVoltage, args)

    def setLNADrainCurrent(self, *args):
        return _omnipy.invoke(self, "setLNADrainCurrent", _0_BiasCorba.BiasModuleCorba._d_setLNADrainCurrent, args)

    __methods__ = ["getTemperature", "getMagnetCurrent", "getMagnetVoltage", "getSISVoltage", "getSISCurrent", "getLNADrainVoltage", "getLNADrainCurrent", "getLNAGateVoltage", "setMagnetCurrent", "setSISVoltage", "setLNADrainVoltage", "setLNADrainCurrent"] + CORBA.Object.__methods__

omniORB.registerObjref(BiasModuleCorba._NP_RepositoryId, _objref_BiasModuleCorba)
_0_BiasCorba._objref_BiasModuleCorba = _objref_BiasModuleCorba
del BiasModuleCorba, _objref_BiasModuleCorba

# BiasModuleCorba skeleton
__name__ = "msipbias.corba.BiasCorba__POA"
class BiasModuleCorba (PortableServer.Servant):
    _NP_RepositoryId = _0_BiasCorba.BiasModuleCorba._NP_RepositoryId


    _omni_op_d = {"getTemperature": _0_BiasCorba.BiasModuleCorba._d_getTemperature, "getMagnetCurrent": _0_BiasCorba.BiasModuleCorba._d_getMagnetCurrent, "getMagnetVoltage": _0_BiasCorba.BiasModuleCorba._d_getMagnetVoltage, "getSISVoltage": _0_BiasCorba.BiasModuleCorba._d_getSISVoltage, "getSISCurrent": _0_BiasCorba.BiasModuleCorba._d_getSISCurrent, "getLNADrainVoltage": _0_BiasCorba.BiasModuleCorba._d_getLNADrainVoltage, "getLNADrainCurrent": _0_BiasCorba.BiasModuleCorba._d_getLNADrainCurrent, "getLNAGateVoltage": _0_BiasCorba.BiasModuleCorba._d_getLNAGateVoltage, "setMagnetCurrent": _0_BiasCorba.BiasModuleCorba._d_setMagnetCurrent, "setSISVoltage": _0_BiasCorba.BiasModuleCorba._d_setSISVoltage, "setLNADrainVoltage": _0_BiasCorba.BiasModuleCorba._d_setLNADrainVoltage, "setLNADrainCurrent": _0_BiasCorba.BiasModuleCorba._d_setLNADrainCurrent}

BiasModuleCorba._omni_skeleton = BiasModuleCorba
_0_BiasCorba__POA.BiasModuleCorba = BiasModuleCorba
omniORB.registerSkeleton(BiasModuleCorba._NP_RepositoryId, BiasModuleCorba)
del BiasModuleCorba
__name__ = "msipbias.corba.BiasCorba"

#
# End of module "BiasCorba"
#
__name__ = "msipbias.corba.biascorba_idl"

_exported_modules = ( "msipbias.corba.BiasCorba", )

# The end.
