# Python stubs generated by omniidl from biascorba.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "BiasCorba"
#
__name__ = "BiasCorba"
_0_BiasCorba = omniORB.openModule("BiasCorba", r"biascorba.idl")
_0_BiasCorba__POA = omniORB.openModule("BiasCorba__POA", r"biascorba.idl")


# interface BiasModuleCorba
_0_BiasCorba._d_BiasModuleCorba = (omniORB.tcInternal.tv_objref, "IDL:BiasCorba/BiasModuleCorba:1.0", "BiasModuleCorba")
omniORB.typeMapping["IDL:BiasCorba/BiasModuleCorba:1.0"] = _0_BiasCorba._d_BiasModuleCorba
_0_BiasCorba.BiasModuleCorba = omniORB.newEmptyClass()
class BiasModuleCorba :
    _NP_RepositoryId = _0_BiasCorba._d_BiasModuleCorba[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_BiasCorba.BiasModuleCorba = BiasModuleCorba
_0_BiasCorba._tc_BiasModuleCorba = omniORB.tcInternal.createTypeCode(_0_BiasCorba._d_BiasModuleCorba)
omniORB.registerType(BiasModuleCorba._NP_RepositoryId, _0_BiasCorba._d_BiasModuleCorba, _0_BiasCorba._tc_BiasModuleCorba)

# BiasModuleCorba operations and attributes
BiasModuleCorba._d_getTemperature = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_float, ), None)
BiasModuleCorba._d_getMagnetCurrent = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_float, ), None)

# BiasModuleCorba object reference
class _objref_BiasModuleCorba (CORBA.Object):
    _NP_RepositoryId = BiasModuleCorba._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def getTemperature(self, *args):
        return _omnipy.invoke(self, "getTemperature", _0_BiasCorba.BiasModuleCorba._d_getTemperature, args)

    def getMagnetCurrent(self, *args):
        return _omnipy.invoke(self, "getMagnetCurrent", _0_BiasCorba.BiasModuleCorba._d_getMagnetCurrent, args)

    __methods__ = ["getTemperature", "getMagnetCurrent"] + CORBA.Object.__methods__

omniORB.registerObjref(BiasModuleCorba._NP_RepositoryId, _objref_BiasModuleCorba)
_0_BiasCorba._objref_BiasModuleCorba = _objref_BiasModuleCorba
del BiasModuleCorba, _objref_BiasModuleCorba

# BiasModuleCorba skeleton
__name__ = "BiasCorba__POA"
class BiasModuleCorba (PortableServer.Servant):
    _NP_RepositoryId = _0_BiasCorba.BiasModuleCorba._NP_RepositoryId


    _omni_op_d = {"getTemperature": _0_BiasCorba.BiasModuleCorba._d_getTemperature, "getMagnetCurrent": _0_BiasCorba.BiasModuleCorba._d_getMagnetCurrent}

BiasModuleCorba._omni_skeleton = BiasModuleCorba
_0_BiasCorba__POA.BiasModuleCorba = BiasModuleCorba
omniORB.registerSkeleton(BiasModuleCorba._NP_RepositoryId, BiasModuleCorba)
del BiasModuleCorba
__name__ = "BiasCorba"

#
# End of module "BiasCorba"
#
__name__ = "biascorba_idl"

_exported_modules = ( "BiasCorba", )

# The end.
