module BiasCorba {
  interface BiasModuleCorba {
    float getTemperature(in short channel, in boolean dbwrite);
    float getMagnetCurrent(in short magnet, in short polar);
    float getMagnetVoltage(in short magnet, in short polar);
    float getSISVoltage(in short sis, in short polar);
    float getSISCurrent(in short sis, in short polar);
    float getLNADrainVoltage(in short lna, in short stage, in short polar);
    float getLNADrainCurrent(in short lna, in short stage, in short polar);
    float getLNAGateVoltage(in short lna, in short stage, in short polar);
    void setMagnetCurrent(in float current, in short magnet, in short polar);
    void setSISVoltage(in float voltage, in short sis, in short polar);
    void setLNADrainVoltage(in float voltage, in short lna, in short stage, in short polar);
    void setLNADrainCurrent(in float current, in short lna, in short stage, in short polar);
    void setLNADrainVoltageCurrent(in float voltage, in float current, in short lna, in short stage, in short polar);
    void turnONLNA(in short polar);
    void turnOFFLNA(in short polar);
  };
};
