# DO NOT EDIT THIS FILE!
#
# Python module BiasCorba__POA generated by omniidl

import omniORB
omniORB.updateModule("BiasCorba__POA")

# ** 1. Stub files contributing to this module
import biascorba_idl

# ** 2. Sub-modules

# ** 3. End
