# DO NOT EDIT THIS FILE!
#
# Python module BiasCorba generated by omniidl

import omniORB
omniORB.updateModule("msipbias.corba.BiasCorba")

# ** 1. Stub files contributing to this module
import msipbias.corba.biascorba_idl
import biascorba_idl

# ** 2. Sub-modules

# ** 3. End
