# DO NOT EDIT THIS FILE!
#
# Python module BiasCorba generated by omniidl

import omniORB
omniORB.updateModule("BiasCorba")

# ** 1. Stub files contributing to this module
from msipbias.corba import biascorba_idl

# ** 2. Sub-modules

# ** 3. End
